version: '3'

services:
  devtools:
    image: ghcr.io/automattic/vip-container-images/dev-tools:0.9
    volumes:
      - devtools:/dev-tools

  nginx:
    image: ghcr.io/automattic/vip-container-images/nginx:1.23.3
    ports:
      - 127.0.0.1::80
    volumes:
      - wp-wordpress:/wp
      - ../:/wp/wp-content
      - wp-uploads:/wp/wp-content/uploads

  php:
    image: ghcr.io/automattic/vip-container-images/php-fpm:8.0

volumes:
  devtools:
  wp-wordpress:
  wp-uploads:
