version: '3.8'

services:
  devtools:
    image: 'ghcr.io/automattic/vip-container-images/dev-tools:0.9'
    volumes:
      - devtools:/dev-tools

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    environment:
      - HOST_UID=${HOST_UID-1000}
      - HOST_GID=${HOST_GID-1000}
    ports:
      - 80:80
    volumes:
      - wp-wordpress:/wp
      - ../:/wp/wp-content
      - wp-uploads:/wp/wp-content/uploads

  php:
    image: ghcr.io/automattic/vip-container-images/php-fpm:8.0

volumes:
  devtools:
  wp-wordpress:
  wp-uploads:
